# Generated by Django 4.2.10 on 2024-03-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_image_remove_post_uploaded_at_post_mage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mage',
        ),
    ]
