# Generated by Django 4.2.10 on 2024-03-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
