# Generated by Django 4.2.10 on 2024-03-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auther',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
